%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.00076
  accelerometer_random_walk: 4.2e-05
  gyroscope_noise_density: 0.000181
  gyroscope_random_walk: 2.0e-06
  model: calibrated
  rostopic: /d435i/imu
  time_offset: 0.0
  update_rate: 100.0
