%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.001056
  accelerometer_random_walk: 0.000289
  gyroscope_noise_density: 0.000183
  gyroscope_random_walk: 2.0e-06
  model: calibrated
  rostopic: /t265/imu
  time_offset: 0.0
  update_rate: 65.0

